### ISSUE TITLE
I'm trying to run this `Connect deep sources` and I get import error

### ISSUE THREAD

**Issue by yacineMahdid** [EtienneCmb/visbrain#55]
I get the following error:
`is_pandas_installed
    raise IOError("pandas not installed. See https://pandas.pydata.org/#"
OSError: pandas not installed. See https://pandas.pydata.org/#best-way-to-install for installation instructions.`
This get resolved by installing pandas, however since I am in a virtualenv it would be nice to have it setup in the requirements since I don't know which version of pandas you tested this library on.

This is what I get by doing `pip install -U visbrain`:
freetype-py==2.1.0.post1
kiwisolver==1.1.0
matplotlib==3.1.1
numpy==1.17.4
Pillow==6.2.1
PyOpenGL==3.1.0
pyparsing==2.4.5
PyQt5==5.13.2
PyQt5-sip==12.7.0
python-dateutil==2.8.1
scipy==1.3.2
six==1.13.0
visbrain==0.4.5
vispy==0.6.2

After installing pandas I have this:
freetype-py==2.1.0.post1
kiwisolver==1.1.0
matplotlib==3.1.1
numpy==1.17.4
**pandas==0.25.3**
Pillow==6.2.1
PyOpenGL==3.1.0
pyparsing==2.4.5
PyQt5==5.13.2
PyQt5-sip==12.7.0
python-dateutil==2.8.1
pytz==2019.3
scipy==1.3.2
six==1.13.0
visbrain==0.4.5
vispy==0.6.2

**Comment by EtienneCmb** [comment]
Hello @yacineMahdid ,

Yes, I understand your point. There's a reason why not all dependencies are required. This is because visbrain is subdivided into several modules and not all of them required pandas. But the website is clear about it, there's a section about [optional dependencies](http://visbrain.org/introduction.html#optional-dependencies)
